version: "3.8"
services:
  identity-system-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - ./.env
    container_name: identity-system-app
